version: '3'
services:
  image2aa_web:
    image: ${REGISTRY:?err}/image2aa_image2aa_web:${TAG}
    command: /usr/bin/image2aa_web
    restart: always
    environment:
      - ROCKET_ENV=prod
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=80
    networks:
      - default
      - applications

networks:
  applications:
    external: true
